import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { SessionProvider } from "next-auth/react"
// import MyApp from "./SessionProvider"

import Layout from "./components/Layout"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Anime List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
